title: Recommender Systems and Social Computing Lab
description: >- # this means to ignore newlines until "baseurl:"
  RecSys, Computational Social Science, Credibility & Trust, Networks, Biases
# Build settings
remote_theme: socialcomplab/cayman
github:
  is_project_page: false
